# Server configuration
server.port=8080

spring.application.name=real-estate

# DATABASE POSTGRES
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Boylata1403@
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# SWAGGER CONFIGURATION
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Authentication and Security
app.jwt.secret=my-super-secret-key-for-jwt-which-is-long-enough-for-hs256
app.jwt.expiration-ms=3600000
app.refresh-token.expiration-days=7